"""add group preferences to trips

Revision ID: 59144bd47c6a
Revises: e842ba2b99cb
Create Date: 2026-10-09 03:50:16.476448

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '59144bd47c6a'
down_revision: Union[str, Sequence[str], None] = 'e842ba2b99cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trip_members_id'), table_name='trip_members')
    op.drop_table('trip_members')
    op.drop_index(op.f('ix_trips_code'), table_name='trips')
    op.drop_index(op.f('ix_trips_id'), table_name='trips')
    op.drop_table('trips')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trips',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('code', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('date_label', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('long_date', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('meetup', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('meetup_full', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('arrival_target', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('wrap_up', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('latitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('longitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('spots_open', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('on_way_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('leader_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['leader_id'], ['users.id'], name=op.f('trips_leader_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('trips_pkey'))
    )
    op.create_index(op.f('ix_trips_id'), 'trips', ['id'], unique=False)
    op.create_index(op.f('ix_trips_code'), 'trips', ['code'], unique=True)
    op.create_table('trip_members',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('trip_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('is_leader', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], name=op.f('trip_members_trip_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('trip_members_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('trip_members_pkey'))
    )
    op.create_index(op.f('ix_trip_members_id'), 'trip_members', ['id'], unique=False)
    # ### end Alembic commands ###
