"""Add preference profile

Revision ID: e842ba2b99cb
Revises: cc4468fecd89
Create Date: 2026-10-06 22:10:41.494477

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e842ba2b99cb'
down_revision: Union[str, Sequence[str], None] = 'cc4468fecd89'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('preference_profiles',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('activity_tags', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('dietary_preferences', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('max_budget', sa.Float(), nullable=False),
    sa.Column('preferred_pace', sa.String(length=50), nullable=False),
    sa.Column('passenger_type', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_preference_profiles_email'), 'preference_profiles', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_preference_profiles_email'), table_name='preference_profiles')
    op.drop_table('preference_profiles')
    # ### end Alembic commands ###
